import express, { Router } from 'express';
import { authRouter } from './server/auth/auth.routes';
import { userRouter } from './server/user/user.routes';
import { clientsRouter } from './server/clients/clients.routes';
import { leadsRouter } from './server/leads/leads.routes';
import { customerRouter } from './server/customer/customer.routes';
import { callHistoryRouter } from './server/call-history/call-history.routes';
import { addressRouter } from './server/address/address.routes';
import { referenceRouter } from './server/reference/reference.routes';
import { employerRouter } from './server/employer/employer.routes';
import { userReporteeRouter } from './server/user-reportee/user-reportee.routes';
import { approvalRouter } from './server/approval/approval.routes';
import { disbursalRouter } from './server/disbursal/disbursal.routes';
import { loanRouter } from './server/loan/loan.routes';
import { collectionRouter } from './server/collection/collection.routes';
import { documentsRouter } from './server/documents/documents.routes';
import { reportsRouter } from './server/reports/reports.routes';
import { creditReportRouter } from './server/credit-report/credit-report.routes';
import { branchTargetRouter } from './server/branch-target/branch-target.routes';
import { sanctionTargetRouter } from './server/sanction-target/sanction-target.routes';
import { customerAssetRouter } from './server/customer-assset/customer-asset.routes';
import { kycRouter } from './server/kyc/kyc.routes';
import { loanCollectionRouter } from './server/loan-collection/loan-collection.routes';
import { adminReportsRouter } from './server/reports/reports.admin.routes';
import { bankRouter } from './server/bank/bank.routes';
import { collectionTimelineRouter } from './server/collection-timeline/collection-timeline.routes';
import { pdVisitRouter } from './server/pd-visit/pd-visit.routes';
import { autoDisbursalRouter } from './server/auto-disbursal/auto-disbursal.routes';
import { auditLogRouter } from './server/audit-logs/audit-logs.routes';
import { reportsDownloadRouter } from './server/reports/reports.download.routes';
import { servicesRouter } from './server/services/services.routes';
import { customerSupportRouter } from './server/tickets/ticket.routes';
import PanRouter from './server/Pan/Pan.Router';

export const crmRouter: Router = express.Router();

crmRouter.use('/auth', authRouter);
crmRouter.use('/user', userRouter);
crmRouter.use('/clients', clientsRouter);
crmRouter.use('/call-history', callHistoryRouter);
crmRouter.use('/customer', customerRouter);
crmRouter.use('/leads', leadsRouter);
crmRouter.use('/address', addressRouter);
crmRouter.use('/reference', referenceRouter);
crmRouter.use('/employer', employerRouter);
crmRouter.use('/kyc', kycRouter);
crmRouter.use('/user-reportee', userReporteeRouter);
crmRouter.use('/approval', approvalRouter);
crmRouter.use('/disbursal', disbursalRouter);
crmRouter.use('/auto-disbursal', autoDisbursalRouter);
crmRouter.use('/loan', loanRouter);
crmRouter.use('/collection', collectionRouter);
crmRouter.use('/documents', documentsRouter);
crmRouter.use('/reports', reportsRouter);
crmRouter.use('/download-reports', reportsDownloadRouter);
crmRouter.use('/credit-report', creditReportRouter);
crmRouter.use('/branch-target', branchTargetRouter);
crmRouter.use('/sanction-target', sanctionTargetRouter);
crmRouter.use('/customer-asset', customerAssetRouter);
crmRouter.use('/loan-collection', loanCollectionRouter);
crmRouter.use('/admin-reports', adminReportsRouter);
crmRouter.use('/bank', bankRouter);
crmRouter.use('/collection-timeline', collectionTimelineRouter);
crmRouter.use('/pd-visit', pdVisitRouter);
crmRouter.use('/audit-logs', auditLogRouter);
crmRouter.use('/services', servicesRouter);
crmRouter.use('/customer-support', customerSupportRouter);

//PAN KYC
crmRouter.use('/Pankyc',PanRouter)
