const {
  AADHAR_VERIFICATION_API_GEN_OTP_ENDPOINT = '',
  AADHAR_VERIFICATION_API_SUBMIT_OTP_ENDPOINT = '',
  AADHAR_VERIFICATION_API_KEY = '',
} = process.env;

const REQUIRED_CONFIG = [
  'AADHAR_VERIFICATION_API_GEN_OTP_ENDPOINT',
  'AADHAR_VERIFICATION_API_SUBMIT_OTP_ENDPOINT',
  'AADHAR_VERIFICATION_API_KEY',
];

REQUIRED_CONFIG.forEach(key => {
  if (!process.env[key]) {
    console.error('[Error] Missing Adhar Kyc Config:', key);
    return process.exit(1);
  }
});

const AADHAR_CONFIG = {
  AADHAR_VERIFICATION_API_GEN_OTP_ENDPOINT,
  AADHAR_VERIFICATION_API_SUBMIT_OTP_ENDPOINT,
  AADHAR_VERIFICATION_API_KEY,
};

export default AADHAR_CONFIG;
